version: '3'
services:
  asterisk:
    build:
      context: .
    image: asterisk
    container_name: asterisk
    volumes:
      - ./configs:/etc/asterisk
    network_mode: "host"
    command: ["/usr/sbin/asterisk", "-fvvv"]
